import { CorrespondenceItem } from './types';
import { generateGoogleCalendarUrl } from './utils/calendar';

export const initialCorrespondenceData: CorrespondenceItem[] = [
  {
    id: 'cor-001',
    trackingNumber: 'COR-2026-1049',
    channel: 'email',
    sender: 'Juzgado Primero Civil del Circuito',
    senderContact: 'notificaciones@juzgadoprimerocivil.gov.co',
    recipient: 'gerencia@tuempresa.com',
    subject: 'NOTIFICACIÓN JUDICIAL: Citación a Audiencia Inicial de Conciliación - Rad. 2026-04982',
    content: 'Por medio de la presente se notifica a las partes del auto proferido por este despacho judicial el 09 de octubre de 2026 en el radicado 2026-04982. Se fija fecha para la audiencia inicial de conciliación y fijación del litigio para el día 15 de octubre de 2026 a las 09:30 AM a través de la plataforma Teams. Se otorga un término de tres (3) días hábiles para radicar excepciones y aportar cuestionario probatorio.',
    receivedAt: '2026-10-09T07:15:00Z',
    status: 'agendado',
    category: 'Legal / Citación Judicial',
    urgency: 'crítica',
    summary: 'El Juzgado Primero Civil notifica auto de citación a Audiencia Inicial de Conciliación y Fijación de Litigio para el 15 de octubre de 2026 a las 09:30 AM vía plataforma Teams. Otorga un plazo perentorio de 3 días hábiles para allegar poder especial y contestar el cuestionario probatorio bajo apremio de sanciones legales.',
    keyPoints: [
      'Audiencia virtual programada para el 15 de Octubre de 2026 a las 09:30 AM.',
      'Plazo fatal de 3 días hábiles (vence 14 de Octubre de 2026) para radicar excepciones previas.',
      'Asistencia obligatoria del representante legal o apoderado con facultades expresas para conciliar.',
      'Sanción pecuniaria de hasta 5 SMLMV en caso de inasistencia injustificada.',
    ],
    actionItems: [
      'Coordinar reunión urgente con el equipo jurídico externo.',
      'Verificar poder debidamente conferido al abogado apoderado.',
      'Radicar memorial de pruebas antes del 14 de Octubre a las 17:00.',
      'Conectarse 15 minutos antes a la sala de Teams indicada en el anexo.',
    ],
    attachments: [
      {
        id: 'att-101',
        name: 'Auto_Citacion_Audiencia_Rad_2026_04982.pdf',
        type: 'pdf',
        size: '1.8 MB',
        textContent: 'REPÚBLICA DE COLOMBIA - RAMA JUDICIAL. JUZGADO PRIMERO CIVIL DEL CIRCUITO. Auto interlocutorio N° 412. Radicación: 2026-04982. Se fija fecha para audiencia del Art. 372 del CGP el día jueves 15 de octubre de 2026, hora 09:30 AM. Enlace virtual: https://teams.microsoft.com/meet/juzgado1-civil-rad4982. Notifíquese a las partes.',
      },
      {
        id: 'att-102',
        name: 'Traslado_Demanda_Anexos_Completos.pdf',
        type: 'pdf',
        size: '4.2 MB',
        textContent: 'Memorial de demanda de responsabilidad contractual y liquidación de perjuicios patrimoniales. Cuantía estimada: $125.000.000 COP.',
      },
    ],
    hasSummonsOrDeadlines: true,
    calendarEvent: {
      id: 'cal-001',
      title: '⚖️ Audiencia Judicial Conciliación - Juzgado 1 Civil (Rad. 2026-04982)',
      description: 'Audiencia de conciliación y fijación de litigio. Radicado 2026-04982. Presencia obligatoria con apoderado especial.',
      startDateTime: '2026-10-15T09:30:00Z',
      endDateTime: '2026-10-15T11:30:00Z',
      locationOrLink: 'https://teams.microsoft.com/meet/juzgado1-civil-rad4982',
      isDeadline: false,
      isScheduled: true,
      scheduledAt: '2026-10-09T07:18:22Z',
      googleCalendarUrl: generateGoogleCalendarUrl(
        '⚖️ Audiencia Judicial Conciliación - Rad. 2026-04982',
        'Audiencia de conciliación obligatoria. Juzgado 1 Civil.',
        'https://teams.microsoft.com/meet/juzgado1-civil-rad4982',
        '2026-10-15T09:30:00Z',
        '2026-10-15T11:30:00Z'
      ),
      reminderMinutesBefore: 1440,
    },
    requiresSignature: false,
    suggestedReply: 'Estimado Juzgado Primero Civil del Circuito: Acusamos recibo formal de la notificación del Auto interlocutorio en el radicado 2026-04982. Informamos que nuestro apoderado judicial radicará el memorial de excepciones y se hará presente en la sala virtual indicada.',
    entities: [
      { name: 'Juzgado Primero Civil del Circuito', type: 'company' },
      { name: 'Rad. 2026-04982', type: 'case_number' },
      { name: '15 de Octubre de 2026', type: 'date' },
      { name: '$125.000.000 COP', type: 'money' },
    ],
    tags: ['Judicial', 'Audiencia', 'Plazo Fatal', 'Conciliación'],
    notificationHistory: [
      {
        id: 'notif-001',
        channel: 'email',
        recipient: 'abogados@tuempresa.com',
        title: 'Alerta Automática: Citación Judicial Rad. 2026-04982',
        message: 'Se ha agendado en su calendario la audiencia para el 15-Oct-2026 a las 09:30 AM y vence plazo de excepciones el 14-Oct.',
        sentAt: '2026-10-09T07:18:30Z',
        status: 'entregado',
        triggerType: 'auto_ingestion',
      },
      {
        id: 'notif-002',
        channel: 'whatsapp',
        recipient: '+57 310 987 6543',
        title: 'Recordatorio WhatsApp',
        message: '⚖️ Alerta CorrespondenciaAI: Notificación judicial del Juzgado 1 Civil radicada. Audiencia agendada para el 15/10/2026 9:30 AM.',
        sentAt: '2026-10-09T07:19:00Z',
        status: 'leído',
        triggerType: 'meeting_reminder',
      },
    ],
    auditTrail: [
      {
        id: 'aud-001',
        timestamp: '2026-10-09T07:15:00Z',
        action: 'Ingesta de Correspondencia',
        actor: 'IMAP Bot (Correo Corporativo)',
        details: 'Correo recibido con 2 adjuntos PDF desde notificaciones@juzgadoprimerocivil.gov.co.',
      },
      {
        id: 'aud-002',
        timestamp: '2026-10-09T07:15:18Z',
        action: 'Análisis IA & Clasificación',
        actor: 'Gemini 3.8 Flash Engine',
        details: 'Clasificado como Legal / Citación Judicial. Urgencia Crítica. Detección de audiencia el 15/10/2026.',
      },
      {
        id: 'aud-003',
        timestamp: '2026-10-09T07:18:22Z',
        action: 'Agendamiento Automático en Calendario',
        actor: 'Calendar Automation Bot',
        details: 'Evento creado para el 15/10/2026 09:30 AM con enlace Teams.',
      },
    ],
  },
  {
    id: 'cor-002',
    trackingNumber: 'COR-2026-1050',
    channel: 'email',
    sender: 'Nexus Tech Global & Partners',
    senderContact: 'legal.contracts@nexustechglobal.io',
    recipient: 'direccion@tuempresa.com',
    subject: 'URGENTE: Contrato Marco de Alianza Tecnológica y Acuerdo NDA para Firma Electrónica',
    content: 'Estimados señores: Remitimos la versión final revisada del Contrato Marco de Prestación de Servicios Cloud y Acuerdo de Confidencialidad (NDA). Solicitamos la suscripción mediante firma electrónica autorizada del Representante Legal a más tardar el viernes 11 de octubre de 2026 a las 18:00 horas para dar curso al despliegue de infraestructura convenido por valor de $48,000 USD.',
    receivedAt: '2026-10-09T06:40:00Z',
    status: 'nuevo',
    category: 'Contratos y Convenios',
    urgency: 'alta',
    summary: 'Nexus Tech remite la versión final revisada del Contrato Marco de Prestación de Servicios en la Nube y Acuerdo de Confidencialidad Bilateral (NDA). Se requiere la firma electrónica del Representante Legal antes del 11 de octubre de 2026 a las 18:00 para dar inicio a los despliegues de infraestructura pactados.',
    keyPoints: [
      'Vigencia de 24 meses renovable automáticamente con preaviso de 60 días.',
      'Valor total convenido: $48,000 USD distribuidos en 12 mensualidades.',
      'Cláusula de confidencialidad estricta y protección de propiedad intelectual recíproca.',
      'Plazo para firma y devolución: viernes 11 de Octubre a las 18:00 horas.',
    ],
    actionItems: [
      'Revisar las cláusulas 4 (Garantías de SLA) y 9 (Penalidad por terminación anticipada).',
      'Realizar la firma electrónica estampando certificado digital de validación.',
      'Enviar comprobante de firma al buzón legal de Nexus Tech.',
    ],
    attachments: [
      {
        id: 'att-201',
        name: 'Contrato_Marco_NexusTech_VFinal_Firmar.pdf',
        type: 'pdf',
        size: '2.4 MB',
        textContent: 'CONTRATO MARCO DE PRESTACIÓN DE SERVICIOS EN INFRAESTRUCTURA CLOUD Y ACUERDO DE CONFIDENCIALIDAD. Entre Nexus Tech Global Inc. y la Empresa Contratante. Cláusula Primera: Objeto. Cláusula Segunda: Valor ($48,000 USD). Cláusula Décima: Aprobación mediante Firma Electrónica con validez plena según Ley 527 de 1999.',
      },
    ],
    hasSummonsOrDeadlines: true,
    calendarEvent: {
      id: 'cal-002',
      title: '⏳ Vencimiento Plazo Firma Contrato Nexus Tech',
      description: 'Límite fatal para estampar firma electrónica en Contrato Marco y NDA por $48,000 USD.',
      startDateTime: '2026-10-11T18:00:00Z',
      endDateTime: '2026-10-11T18:30:00Z',
      locationOrLink: 'Panel CorrespondenciaAI - Módulo de Firma',
      isDeadline: true,
      isScheduled: false,
      googleCalendarUrl: generateGoogleCalendarUrl(
        '⏳ Vencimiento Plazo Firma Contrato Nexus Tech',
        'Límite fatal para estampar firma electrónica en Contrato Marco.',
        'Panel CorrespondenciaAI',
        '2026-10-11T18:00:00Z',
        '2026-10-11T18:30:00Z'
      ),
      reminderMinutesBefore: 120,
    },
    requiresSignature: true,
    signatureDetails: {
      documentTitle: 'Contrato Marco de Alianza Tecnológica & NDA Nexus',
      signerRole: 'Representante Legal / CEO',
      expirationDate: '2026-10-11T18:00:00Z',
      clausesToAccept: [
        'Acepto los términos de servicio y nivel de disponibilidad SLA del 99.9%.',
        'Declaro tener facultades estatutarias suficientes para obligar a la compañía.',
        'Autorizo el estampado criptográfico y la generación del certificado SHA-256.',
      ],
    },
    suggestedReply: 'Estimado equipo legal de Nexus Tech Global: Hemos recibido el Contrato Marco y NDA. En este momento procedemos con la validación de firmas en nuestra plataforma digital para remitir el certificado de firma debidamente estampado.',
    entities: [
      { name: 'Nexus Tech Global & Partners', type: 'company' },
      { name: '$48,000 USD', type: 'money' },
      { name: '11 de Octubre de 2026', type: 'date' },
      { name: 'Ley 527 de 1999', type: 'case_number' },
    ],
    tags: ['Contrato', 'Firma Pendiente', 'NDA', 'Cloud Services'],
    notificationHistory: [
      {
        id: 'notif-003',
        channel: 'email',
        recipient: 'direccion@tuempresa.com',
        title: 'Firma Requerida: Contrato Marco Nexus Tech',
        message: 'Tiene 1 documento pendiente de firma electrónica con fecha límite 11-Octubre.',
        sentAt: '2026-10-09T06:42:00Z',
        status: 'entregado',
        triggerType: 'signature_request',
      },
    ],
    auditTrail: [
      {
        id: 'aud-004',
        timestamp: '2026-10-09T06:40:00Z',
        action: 'Ingesta de Correo Electrónico',
        actor: 'Mail Inbound Worker',
        details: 'Correo recibido desde legal.contracts@nexustechglobal.io.',
      },
      {
        id: 'aud-005',
        timestamp: '2026-10-09T06:40:15Z',
        action: 'Análisis IA & Extracción de Cláusulas',
        actor: 'Gemini 3.8 Flash Engine',
        details: 'Detectada necesidad de firma electrónica obligatoria antes del 11/10/2026.',
      },
    ],
  },
  {
    id: 'cor-003',
    trackingNumber: 'COR-2026-1051',
    channel: 'whatsapp',
    sender: 'Dra. Elena Ramos (Presidenta de Junta Directiva)',
    senderContact: '+57 318 456 7890',
    recipient: '+57 300 123 4567',
    subject: 'Convocatoria Urgente: Sesión Extraordinaria de Junta Directiva',
    content: 'Estimados miembros de la Junta: Por medio de la presente me permito convocar a Sesión Extraordinaria de Junta Directiva para el próximo lunes 14 de octubre de 2026 a las 15:00 horas (3:00 PM) en la Sala de Juntas Principal y enlace Google Meet: https://meet.google.com/xyz-junta-extraordinaria. Trataremos el presupuesto de cierre de año y la propuesta de inversión Serie A. Favor confirmar asistencia.',
    receivedAt: '2026-10-09T08:05:00Z',
    status: 'agendado',
    category: 'Convocatoria a Reunión',
    urgency: 'alta',
    summary: 'La Presidenta de la Junta Directiva envía convocatoria formal por WhatsApp para Sesión Extraordinaria de Junta Directiva el próximo lunes 14 de octubre de 2026 a las 15:00 horas (3:00 PM). El orden del día incluye la revisión del presupuesto Q4 y la aprobación de la ronda de inversión Serie A.',
    keyPoints: [
      'Reunión convocada para el lunes 14 de octubre de 2026, 3:00 PM a 5:30 PM.',
      'Modalidad mixta: Sala de Juntas Principal y enlace Google Meet para miembros remotos.',
      'Tema central: Presentación de estados financieros preliminares y voto para Serie A.',
      'Se adjuntó la orden del día oficial y los estados financieros consolidados.',
    ],
    actionItems: [
      'Confirmar quórum por este mismo canal de WhatsApp.',
      'Preparar la presentación ejecutiva del informe financiero Q3.',
      'Revisar el archivo adjunto con el term sheet propuesto por los inversionistas.',
    ],
    attachments: [
      {
        id: 'att-301',
        name: 'Orden_del_Dia_Junta_Extraordinaria_Oct14.pdf',
        type: 'pdf',
        size: '980 KB',
        textContent: 'JUNTA DIRECTIVA - SESIÓN EXTRAORDINARIA N° 84. Fecha: 14 de Octubre de 2026. Hora: 15:00 COL. Orden del día: 1. Verificación del quórum. 2. Presentación resultados Q3. 3. Votación autorización de endeudamiento y emisión. 4. Proposiciones y varios.',
      },
      {
        id: 'att-302',
        name: 'Estados_Financieros_Consolidados_Q3.xlsx',
        type: 'docx',
        size: '1.2 MB',
        textContent: 'Resumen financiero consolidado con ingresos operacionales brutos por $1.420.000 USD y EBITDA positivo del 18.4%.',
      },
    ],
    hasSummonsOrDeadlines: true,
    calendarEvent: {
      id: 'cal-003',
      title: '👔 Sesión Extraordinaria de Junta Directiva (Presupuesto Q4 & Serie A)',
      description: 'Sesión N° 84 de Junta Directiva. Revisión de balance Q3 y votación de inversión Serie A. Enlace Meet adjunto.',
      startDateTime: '2026-10-14T15:00:00Z',
      endDateTime: '2026-10-14T17:30:00Z',
      locationOrLink: 'https://meet.google.com/xyz-junta-extraordinaria',
      isDeadline: false,
      isScheduled: true,
      scheduledAt: '2026-10-09T08:06:12Z',
      googleCalendarUrl: generateGoogleCalendarUrl(
        '👔 Sesión Extraordinaria de Junta Directiva',
        'Sesión N° 84 de Junta Directiva. Revisión balance y Serie A.',
        'https://meet.google.com/xyz-junta-extraordinaria',
        '2026-10-14T15:00:00Z',
        '2026-10-14T17:30:00Z'
      ),
      reminderMinutesBefore: 120,
    },
    requiresSignature: false,
    suggestedReply: 'Estimada Dra. Elena, confirmo recibido y asistencia a la Sesión Extraordinaria de Junta del lunes 14 de octubre a las 3:00 PM. Tendremos listos los informes de Q3 y la documentación para la deliberación.',
    entities: [
      { name: 'Dra. Elena Ramos', type: 'person' },
      { name: 'Junta Directiva', type: 'company' },
      { name: '14 de Octubre de 2026', type: 'date' },
      { name: 'Serie A ($1.42M USD)', type: 'money' },
    ],
    tags: ['WhatsApp', 'Junta Directiva', 'Reunión', 'Gobierno Corporativo'],
    notificationHistory: [
      {
        id: 'notif-004',
        channel: 'whatsapp',
        recipient: '+57 318 456 7890',
        title: 'Confirmación WhatsApp enviada',
        message: 'Respuesta generada y confirmada a la Dra. Elena Ramos.',
        sentAt: '2026-10-09T08:07:00Z',
        status: 'leído',
        triggerType: 'manual_dispatch',
      },
    ],
    auditTrail: [
      {
        id: 'aud-006',
        timestamp: '2026-10-09T08:05:00Z',
        action: 'Ingesta de Mensaje WhatsApp Business',
        actor: 'WhatsApp Webhook Listener',
        details: 'Mensaje entrante con 2 archivos adjuntos desde +57 318 456 7890.',
      },
      {
        id: 'aud-007',
        timestamp: '2026-10-09T08:05:12Z',
        action: 'Análisis IA & Sincronización Automática',
        actor: 'Gemini 3.8 Flash Engine',
        details: 'Convocatoria detectada. Agendado automáticamente para el 14/10/2026 a las 15:00.',
      },
    ],
  },
  {
    id: 'cor-004',
    trackingNumber: 'COR-2026-1052',
    channel: 'email',
    sender: 'DIAN - Dirección de Impuestos y Aduanas Nacionales',
    senderContact: 'notificaciones.electronicas@dian.gov.co',
    recipient: 'tributaria@tuempresa.com',
    subject: 'REQUERIMIENTO ORDINARIO: Solicitud de Información Exógena e Inconsistencias IVA Periodo 4',
    content: 'DIAN - Dirección de Impuestos y Aduanas Nacionales. Notificación de Requerimiento Ordinario N° 2026-REQ-883. Se solicita al contribuyente suministrar información detallada y soportes de retenciones en la fuente e IVA correspondiente al periodo 4 dentro del término improrrogable de 10 días hábiles (vencimiento 23 de octubre de 2026) a través del portal institucional.',
    receivedAt: '2026-10-09T05:30:00Z',
    status: 'nuevo',
    category: 'Tributario y Fiscal',
    urgency: 'alta',
    summary: 'La autoridad tributaria notifica Requerimiento Ordinario de Información N° 2026-REQ-883 solicitando sustento de retenciones en la fuente e inconsistencias de IVA del bimestre anterior. Concede plazo legal improrrogable de 10 días hábiles (vencimiento 23 de octubre de 2026) para responder a través de los servicios informáticos electrónicos.',
    keyPoints: [
      'Requerimiento Ordinario N° 2026-REQ-883.',
      'Plazo fatal para radicar respuesta: 23 de octubre de 2026 a las 16:00 horas.',
      'Aplica sobre el periodo gravable 2026-Bimestre 4.',
      'Posible sanción por no enviar información prevista en el Art. 651 del Estatuto Tributario.',
    ],
    actionItems: [
      'Remitir expediente al Contador General y Revisor Fiscal.',
      'Conciliar las facturas electrónicas de compra con los soportes de retención.',
      'Generar los formatos XML requeridos y cargarlos en el portal DIAN.',
    ],
    attachments: [
      {
        id: 'att-401',
        name: 'Requerimiento_Ordinario_DIAN_2026_REQ_883.pdf',
        type: 'pdf',
        size: '1.5 MB',
        textContent: 'DIAN - SUBDIRECCIÓN DE FISCALIZACIÓN TRIBUTARIA. Se requiere al contribuyente para que en el término de 10 días hábiles allegue libros auxiliares de contabilidad y relación de retenciones practicadas.',
      },
    ],
    hasSummonsOrDeadlines: true,
    calendarEvent: {
      id: 'cal-004',
      title: '🚨 Vencimiento Plazo Respuesta DIAN (Requerimiento 883)',
      description: 'Límite fatal de 10 días para cargar en la DIAN la respuesta al Requerimiento Ordinario 2026-REQ-883.',
      startDateTime: '2026-10-23T16:00:00Z',
      endDateTime: '2026-10-23T17:00:00Z',
      locationOrLink: 'Portal Muisca DIAN',
      isDeadline: true,
      isScheduled: false,
      googleCalendarUrl: generateGoogleCalendarUrl(
        '🚨 Vencimiento Plazo Respuesta DIAN (Req 883)',
        'Plazo legal improrrogable respuesta DIAN.',
        'Portal Muisca DIAN',
        '2026-10-23T16:00:00Z',
        '2026-10-23T17:00:00Z'
      ),
      reminderMinutesBefore: 1440,
    },
    requiresSignature: false,
    suggestedReply: 'A la División de Fiscalización DIAN: Se acusa recibo del Requerimiento Ordinario N° 2026-REQ-883. Nuestra gerencia tributaria se encuentra consolidando los soportes requeridos para radicación oportuna dentro del término legal fijado.',
    entities: [
      { name: 'DIAN', type: 'company' },
      { name: '2026-REQ-883', type: 'case_number' },
      { name: '23 de Octubre de 2026', type: 'date' },
      { name: 'Art. 651 ET', type: 'case_number' },
    ],
    tags: ['Tributario', 'DIAN', 'Fiscalización', 'Plazo Fatal'],
    notificationHistory: [],
    auditTrail: [
      {
        id: 'aud-008',
        timestamp: '2026-10-09T05:30:00Z',
        action: 'Ingesta Notificación DIAN',
        actor: 'Mail Inbound Worker',
        details: 'Correo certificado recibido desde notificaciones.electronicas@dian.gov.co.',
      },
      {
        id: 'aud-009',
        timestamp: '2026-10-09T05:30:11Z',
        action: 'Análisis IA & Detección de Plazo',
        actor: 'Gemini 3.8 Flash Engine',
        details: 'Identificado plazo fatal de 10 días hábiles con fecha de vencimiento 23/10/2026.',
      },
    ],
  },
  {
    id: 'cor-005',
    trackingNumber: 'COR-2026-1053',
    channel: 'whatsapp',
    sender: 'Carlos Mendoza (Líder de Operaciones)',
    senderContact: '+57 320 891 2345',
    recipient: '+57 300 123 4567',
    subject: 'Solicitud Aprobación: Adición Presupuestal para Licencias de Software y Seguridad',
    content: 'Hola Gerencia, te escribo para solicitar el visto bueno y firma de la orden de compra PO-2026-094 por $6.500 USD para la renovación del software de seguridad perimetral de la empresa. Tenemos plazo de descuento del 15% hasta el 20 de octubre. Te adjunto el PDF de la orden para tu firma electrónica. ¡Quedo atento!',
    receivedAt: '2026-10-08T19:20:00Z',
    status: 'procesado',
    category: 'Financiero y Presupuesto',
    urgency: 'media',
    summary: 'El Líder de Operaciones solicita visto bueno y firma electrónica para la orden de compra de renovación de licencias de seguridad perimetral (Firewall & EDR) por un valor de $6.500 USD antes de fin de mes para aprovechar un descuento del 15%.',
    keyPoints: [
      'Renovación anual de suites de ciberseguridad perimetral para 85 colaboradores.',
      'Monto total de la orden: $6.500 USD (con 15% de descuento por pronto pago).',
      'Plazo de cotización preferencial vigente hasta el 20 de octubre.',
    ],
    actionItems: [
      'Revisar la cotización adjunta de Fortinet y CrowdStrike.',
      'Aprobar y firmar la orden de compra en el sistema.',
      'Notificar a tesorería para la programación del desembolso.',
    ],
    attachments: [
      {
        id: 'att-501',
        name: 'Orden_Compra_PO_2026_094_Seguridad.pdf',
        type: 'pdf',
        size: '640 KB',
        textContent: 'ORDEN DE COMPRA N° PO-2026-094. Proveedor: CyberShield Latam. Ítem: Renovación Anual Licenciamiento Endpoint & Firewall. Total: $6.500 USD. Requiere aprobación de Gerencia.',
      },
    ],
    hasSummonsOrDeadlines: false,
    requiresSignature: true,
    signatureDetails: {
      documentTitle: 'Orden de Compra PO-2026-094 - Ciberseguridad',
      signerRole: 'Director Financiero / Gerente',
      expirationDate: '2026-10-20T23:59:00Z',
      clausesToAccept: [
        'Apruebo la afectación de la partida presupuestal de TI.',
        'Confirmo la aplicación del descuento por pronto pago.',
      ],
    },
    suggestedReply: 'Hola Carlos, revisada la cotización y la orden PO-2026-094. Procedo a estampar la firma de aprobación en la plataforma para que tesorería procese la orden antes del vencimiento del descuento.',
    entities: [
      { name: 'Carlos Mendoza', type: 'person' },
      { name: '$6.500 USD', type: 'money' },
      { name: 'PO-2026-094', type: 'case_number' },
      { name: 'CyberShield Latam', type: 'company' },
    ],
    tags: ['WhatsApp', 'Finanzas', 'Aprobación', 'Ciberseguridad'],
    notificationHistory: [],
    auditTrail: [
      {
        id: 'aud-010',
        timestamp: '2026-10-08T19:20:00Z',
        action: 'Ingesta WhatsApp',
        actor: 'WhatsApp Webhook Listener',
        details: 'Mensaje con archivo PDF recibido de Carlos Mendoza.',
      },
    ],
  },
];
